CREATE TABLE IF NOT EXISTS FINKRATZEN.CHECKING(
    ID VARCHAR(100) NOT NULL,
    POSTING_DATE DATE NOT NULL, 
    AMOUNT DECIMAL(19, 4), 
    MERCHANT VARCHAR(200), 
    RECORD_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP() 
);    

ALTER TABLE FINKRATZEN.CHECKING ADD CONSTRAINT IF NOT EXISTS FINKRATZEN.CHECKING_PK PRIMARY KEY(ID); 
