-- Original finkratzen schema
-- Generated via:
-- script nopasswords nosettings to '/home/pi/boa_checking.sql' table finkratzen.BOA_CHECKING;
--
CREATE SCHEMA IF NOT EXISTS FINKRATZEN AUTHORIZATION SA;       

--CREATE SEQUENCE FINKRATZEN.BACKUP_SEQ START WITH 4486 MINVALUE 0;              

--CREATE SEQUENCE FINKRATZEN.SYSTEM_SEQUENCE_BDFE30D5_2A78_42B1_9C09_1B51BC9FE9E5 START WITH 882934 BELONGS_TO_TABLE;            

CREATE CACHED TABLE IF NOT EXISTS FINKRATZEN.BOA_CHECKING(
    BANK_ID VARCHAR(100) NOT NULL SELECTIVITY 100,
    POSTING_DATE DATE NOT NULL SELECTIVITY 12,
    AMOUNT DECIMAL(19, 4) SELECTIVITY 56,
    DESCRIPTION VARCHAR(200) SELECTIVITY 73,
    RECORD_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP() SELECTIVITY 100
);    

ALTER TABLE FINKRATZEN.BOA_CHECKING ADD CONSTRAINT IF NOT EXISTS FINKRATZEN.CONSTRAINT_8 PRIMARY KEY(BANK_ID, POSTING_DATE); 
